### ISSUE TITLE
-llapack missing?

### ISSUE THREAD

**Issue by FabioDioguardi** [demichie/IMEX_SfloW2D#8]
Dear developers,

I have tried compiling the latest release of the code on our Ubuntu machine by I got the following error message:

_dioguardi@labvolc:~/Software/IMEX_SfloW2D-1.0.0$ make
Making all in src
make[1]: ingresso nella directory «/home/dioguardi/Software/IMEX_SfloW2D-1.0.0/src»
gfortran  -Wunused -O3 -funroll-all-loops -c -o complexify.o complexify.f90
gfortran  -Wunused -O3 -funroll-all-loops -c -o parameters_2d.o parameters_2d.f90
gfortran  -Wunused -O3 -funroll-all-loops -c -o geometry_2d.o geometry_2d.f90
gfortran  -Wunused -O3 -funroll-all-loops -c -o constitutive_2d.o constitutive_2d.f90
gfortran  -Wunused -O3 -funroll-all-loops -c -o solver_2d.o solver_2d.f90
gfortran  -Wunused -O3 -funroll-all-loops -c -o init_2d.o init_2d.f90
gfortran  -Wunused -O3 -funroll-all-loops -c -o inpout_2d.o inpout_2d.f90
gfortran  -Wunused -O3 -funroll-all-loops -c -o IMEX_Sflow_2d.o IMEX_Sflow_2d.f90
gfortran  -Wunused -O3 -funroll-all-loops   -o IMEX_SfloW2D complexify.o parameters_2d.o geometry_2d.o constitutive_2d.o solver_2d.o init_2d.o inpout_2d.o IMEX_Sflow_2d.o  -lm -llapack
/usr/bin/ld: impossibile trovare -llapack_

I compiled several other fortran software on that computer without this issue, which I see for the first time. 
Any suggestion?

Grazie
Fabio

PS: ciao Mattia! :)

**Comment by demichie** [comment]
Before compiling the code, please be sure that the following libraries are installed on your system:

liblapack-dev
libopenblas-dev

Ciao
Mattia

P.S. Please check also:

https://github.com/demichie/IMEX_SfloW2D_v2

**Comment by FabioDioguardi** [comment]
Thank you very much!

Fabio
